FROM python:3.12.10-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl

RUN pip install --no-cache-dir uv>=0.6.6

COPY . .

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=20 \
  # no-dd-sa:docker-best-practices/avoid-http
  CMD curl -f "http://$host:$port" || exit 1

CMD ["uv", "run", "/app/main.py"]
