import os
os.environ["OPENAI_API_KEY"] = "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"

from openai import OpenAI
import json

client = OpenAI()

# 1. Define a list of callable tools for the model
tools = [
    {
        "type": "function",
        "name": "get_horoscope",
        "description": "Get today's horoscope for an astrological sign.",
        "parameters": {
            "type": "object",
            "properties": {
                "sign": {
                    "type": "string",
                    "description": "An astrological sign like Taurus or Aquarius",
                },
            },
            "required": ["sign"],
        },
    },
]

def get_horoscope(sign):
    return f"{sign}: Next Tuesday you will befriend a baby otter."

# Create a running input list we will add to over time
input_list = [
    {"role": "user", "content": "What is horoscope?"},
    {"role": "assistant", "content": "A horoscope is a forecast of a person's future based on the positions of the stars and planets at the time of their birth."},
    {"role": "user", "content": "What is my horoscope? I am an Aquarius."}
]

# 2. Prompt the model with tools defined
response = client.responses.create(
    model="gpt-5-mini",
    tools=tools,
    input=input_list,
)

# Save function call outputs for subsequent requests

for item in response.output:
    if item.type == "function_call":
        if item.name == "get_horoscope":
            # 3. Execute the function logic for get_horoscope
            horoscope = get_horoscope(json.loads(item.arguments))
            
            input_list.append({
                "type": "function_call",
                "name": item.name,
                "call_id": item.call_id,
                "arguments": item.arguments,
            })

            # 4. Provide function call results to the model
            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": horoscope,
            })

print("Final input:")
print(input_list)

response = client.responses.create(
    model="gpt-5-mini",
    instructions="Respond only with a horoscope generated by a tool.",
    tools=tools,
    input=input_list,
)

# 5. The model should be able to give a response!
print("Final output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)